### ISSUE TITLE
No module named 'mj_envs'

### ISSUE THREAD

**Issue by superspace666** [aravindr93/hand_dapg#13]
Hello,
I have completed the step 1 and step 2 of the getting started process, I can also run the demo of robohive: python -m robohive.utils.examine_env -e FrankaReachRandom-v0. But when I try to run the step 3: python utils/visualize_demos.py --env_name relocate-v0, It still tell me that: ModuleNotFoundError: No module named 'mj_envs'.

**Comment by aravindr93** [comment]
Hi, sorry for the delay. The package mj_envs has been renamed into robohive. If you can use the `stable` branch of robohive (formerly mj_envs), it should have the correct package configuration and naming conventions.

**Comment by ismarou** [comment]
Hello,

I indeed cloned the latest stable branch but the MuJoCo binding installation seems to be breaking. The error is the following:

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          See c_warning_callback, which is the C wrapper to the user defined function
          '''
          global py_warning_callback
          global mju_user_warning
          py_warning_callback = warn
          mju_user_warning = c_warning_callback
                             ^
      ------------------------------------------------------------
      
      mujoco_py/cymj.pyx:92:23: Cannot assign type 'void (const char *) except * nogil' to 'void (*)(const char *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (const char *) except * nogil'.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          See c_warning_callback, which is the C wrapper to the user defined function
          '''
          global py_error_callback
          global mju_user_error
          py_error_callback = err_callback
          mju_user_error = c_error_callback
                           ^
      ------------------------------------------------------------
      
      mujoco_py/cymj.pyx:127:21: Cannot assign type 'void (const char *) except * nogil' to 'void (*)(const char *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (const char *) except * nogil'.
      Removing old mujoco_py cext /tmp/pip-install-2myto1ja/mujoco-py_04378f34131f4ba9a8640e9223bacf58/mujoco_py/generated/cymj_2.0.2.13_39_linuxcpuextensionbuilder_39.so
      Compiling /tmp/pip-install-2myto1ja/mujoco-py_04378f34131f4ba9a8640e9223bacf58/mujoco_py/cymj.pyx because it changed.
      [1/1] Cythonizing /tmp/pip-install-2myto1ja/mujoco-py_04378f34131f4ba9a8640e9223bacf58/mujoco_py/cymj.pyx

I have tried with bith mujoco200 and mujoco210 in the proper path ~/.mujoco/mujocoX and I have properly installed mujoco_py before.

Is there anything that I am missing?
