### ISSUE TITLE
This implementation may ignore the heuristic weighting scheme. 

### ISSUE THREAD

**Issue by sunyasheng** [aravindr93/hand_dapg#4]
I output the variable self.iter_count in class DAPG of dapg.py and find that this variable never changes.
It means that             
```
demo_adv = self.lam_0 * (self.lam_1 ** self.iter_count) * np.ones(demo_obs.shape[0])
```
this lines of code will actually always amount to 
```
demo_adv = self.lam_0 * np.ones(demo_obs.shape[0])
```

**Comment by aravindr93** [comment]
Thanks for the good catch! In our earlier implementations, we were incrementing the counter externally in the train script, but forgot to include that with the public version of repo. We have now updated the algorithm `dapg.py` to increase the counter there, which is cleaner with the current setup.
